fix apex shit

diff --git a/system/bin/bootlinux_init b/system/bin/bootlinux_init
--- a/system/bin/bootlinux_init
+++ b/system/bin/bootlinux_init
@@ -1,19 +1,20 @@
 #!/system/bin/sh
 
 # shellcheck disable=SC3045
-if [ -n "$(type -p busybox)" ]; then
+if [ -d /sbin/.magisk/busybox ]; then
+    busybox="/sbin/.magisk/busybox/busybox";
+    export busybox;
+elif [ -n "$(type -p busybox)" ]; then
     busybox=$(type -p busybox)
     export busybox
+elif [ -x /system/xbin/busybox ]; then
+    export busybox=/system/xbin/busybox
+elif [ -x /system/bin/busybox ]; then
+    export busybox=/system/bin/busybox
 else
-    if [ -x /system/xbin/busybox ]; then
-	    export busybox=/system/xbin/busybox
-    elif [ -x /system/bin/busybox ]; then
-	    export busybox=/system/bin/busybox
-    else
-	    echo "Busybox not found!  Install it, dummy!"
-	    log "Busybox not found!  Install it, dummy!"
-	    exit 1
-    fi
+    echo "Busybox not found!  Install it, dummy!"
+    log "Busybox not found!  Install it, dummy!"
+    exit 1
 fi
 
 ######### CHECK FOR ROOT #########
@@ -148,11 +149,13 @@ mount_linux_chroot() {
     mkdir -p $mnt/external_sd
 
     mkdir -p $mnt/apex
-    cd "/apex" || { echo "Directory /apex not found."; exit 1; }
-    for f in *; do
-        mkdir -p "$mnt/apex/$f"
-    done
-    cd - 2>&1 > /dev/null
+    if [ -d /apex ]; then
+        cd "/apex" || { echo "Directory /apex not found."; exit 1; }
+        for f in *; do
+            mkdir -p "$mnt/apex/$f"
+        done
+        cd - 2>&1 > /dev/null
+    fi
 
     mkdir -p $mnt/data/data
     mkdir -p $mnt/data/dalvik-cache
